apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-search-app
  labels:
    app: number-search-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: number-search-app
  template:
    metadata:
      labels:
        app: number-search-app
    spec:
      containers:
      - name: number-search-app
        image: number-search-app:latest
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        env:
        - name: ELASTIC_APM_SERVER_URLS
          value: "http://apm-server:8200"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "number-search-app"
        - name: ELASTIC_APM_ENVIRONMENT
          value: "production"