services:
  number-search-app:
    build: .
    environment:
      - ELASTIC_APM_SERVER_URLS=http://apm-server:8200
      - ELASTIC_APM_SERVICE_NAME=number-search-app
      - ELASTIC_APM_ENVIRONMENT=development
    depends_on:
      - apm-server
    stdin_open: true
    tty: true
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.0
    command: >
      apm-server -e
        -E setup.kibana.host=kibana:5601
        -E setup.kibana.enabled=true
        -E setup.template.enabled=true
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
        -E apm-server.host="0.0.0.0:8200"
        -E apm-server.kibana.host=kibana:5601
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch
      - kibana

networks:
  default:
    driver: bridge

volumes:
  esdata:
    driver: local