name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fonte
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Teste
        run: dotnet test --no-build

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: joiltonsantos/number-search-app:${{ github.sha }}
          
      - name: Checkout repositório de infraestrutura
        uses: actions/checkout@v3
        with:
          repository: JoiltonSantos/NumberSearchApp-Infra
          token: ${{ secrets.PAT_TOKEN }}
          path: infra
          
      - name: Atualizar tag da imagem no manifesto
        run: |
          cd infra
          sed -i 's|image: joiltonsantos/number-search-app:.*|image: joiltonsantos/number-search-app:${{ github.sha }}|g' number-search-app.yaml
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          if [[ -n $(git status -s) ]]; then
            git add number-search-app.yaml
            git commit -m "Atualizar tag da imagem para ${{ github.sha }}"
            git push
          else
            echo "Nenhuma alteração detectada no manifesto"
          fi